spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  aop:
    proxy-target-class: true
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 5000
      "[mail.smtp.writetimeout]": 5000


kakao:
  admin-key: ${KAKAO_ADMIN_KEY}
  unlink-uri: https://kapi.kakao.com/v1/user/unlink
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-uri: ${KAKAO_TOKEN_URI}
  userinfo-uri: ${KAKAO_USER_INFO}


jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_EXPIRATION}
    header: Authorization
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
    header: RefreshToken

feedback:
  hash:
    secret: ${FEEDBACK_HASH_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_IAM_ACCESS_KEY}
      secret-key: ${AWS_S3_IAM_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}

springdoc:
  swagger-ui:
    with-credentials: true

server:
  forward-headers-strategy: framework

logging:
  forwarding:
    enabled: false
    url: ${LOG_FORWARD_URL:}
    timeout-ms: 3000
    max-retries: 1
