package com.tavemakers.surf.domain.activity.entity.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

import static com.tavemakers.surf.domain.activity.entity.enums.ActivityCategory.*;
import static com.tavemakers.surf.domain.activity.entity.enums.AppliedTarget.INDIVIDUAL;
import static com.tavemakers.surf.domain.activity.entity.enums.AppliedTarget.TEAM;
import static com.tavemakers.surf.domain.activity.entity.enums.ScoreType.*;

@Getter
@AllArgsConstructor
public enum ActivityType {

    /** REWARD (상점): 순서는 18기 회칙 문서와 같음 */
    EARLY_BIRD("행사 얼리버드", 5, REWARD, INDIVIDUAL, REGULAR_SESSION),

    ENGAGE_AFTER_PARTY("뒷풀이 참여", 5, REWARD, INDIVIDUAL, ACTIVITY),
    CREATE_FLASH_MEETUP("번개모임 주최", 10, REWARD, INDIVIDUAL, ACTIVITY),
    ENGAGE_FLASH_MEETUP("번개모임 참여", 5, REWARD, INDIVIDUAL, ACTIVITY),
    SHARE_INFORMATION_AGIT("기술 정보 공유", 5, REWARD, INDIVIDUAL, ACTIVITY),
    ENGAGE_TECH_SEMINAR("기술 세미나 참여", 10, REWARD, INDIVIDUAL, ACTIVITY),
    PRESENT_OUTLINE("기획안 발표", 10, REWARD, INDIVIDUAL, ACTIVITY),

    TEAM_LEADER("팀장 역할 수행", 10, REWARD, INDIVIDUAL, ACTIVITY),

    UPLOAD_TAVE_REVIEW("TAVE 활동 후기 업로드", 10, REWARD, INDIVIDUAL, ACTIVITY),
    UPLOAD_SUCCESS_STORY("합격 수기 업로드", 10, REWARD, INDIVIDUAL, ACTIVITY),

    UPLOAD_INSTAGRAM_STORY("인스타 스토리 업로드", 3, REWARD, INDIVIDUAL, ACTIVITY),
    ENGAGE_SATISFACTION_SURVEY("만족도 조사 참여", 3, REWARD, INDIVIDUAL, ACTIVITY),

    WRITE_WIL("기술 블로그(WIL) 작성", 3, REWARD, INDIVIDUAL, ACTIVITY),

    CREATE_SOCIAL_CLUB("소그룹 생성", 15, REWARD, INDIVIDUAL, ACTIVITY),
    ENGAGE_SOCIAL_CLUB("소그룹 활동 참여", 5, REWARD, INDIVIDUAL, ACTIVITY),


    /** PENALTY: INDIVIDUAL (개인 벌점, 순서는 18기 회칙 문서와 같음) */
    TEAM_LATE("스터디/프로젝트 지각", 0, PENALTY, INDIVIDUAL, STUDY_ON_PERSONAL),

    STUDY_LATE_5_TO_9("스터디 지각 (5~9분)", -5, PENALTY, INDIVIDUAL, STUDY_ON_PERSONAL),
    STUDY_LATE_10_TO_19("스터디 지각 (10~19분)", -10, PENALTY, INDIVIDUAL, STUDY_ON_PERSONAL),
    STUDY_LATE_20_TO_29("스터디 지각 (20~29분)", -15, PENALTY, INDIVIDUAL, STUDY_ON_PERSONAL),
    PROJECT_LATE_5_TO_9("프로젝트 지각 (5~9분)", -5, PENALTY, INDIVIDUAL, PROJECT_ON_PERSONAL),
    PROJECT_LATE_10_TO_19("프로젝트 지각 (10~19분)", -10, PENALTY, INDIVIDUAL, PROJECT_ON_PERSONAL),
    PROJECT_LATE_20_TO_29("프로젝트 지각 (20~29분)", -15, PENALTY,INDIVIDUAL, PROJECT_ON_PERSONAL),

    TEAM_ABSENCE("스터디/프로젝트 결석", 0, PENALTY, INDIVIDUAL, PROJECT_ON_PERSONAL),

    STUDY_ABSENCE("스터디 결석", -30, PENALTY, INDIVIDUAL, STUDY_ON_PERSONAL),
    PROJECT_ABSENCE("프로젝트 결석", -30, PENALTY, INDIVIDUAL, PROJECT_ON_PERSONAL),

    SESSION_LATE("정규 세션 지각", 0, PENALTY, INDIVIDUAL, REGULAR_SESSION),

    SESSION_LATE_1_TO_10("정규 세션 지각 (1~10분)", -10, PENALTY, INDIVIDUAL, REGULAR_SESSION),
    SESSION_LATE_11_TO_20("정규 세션 지각 (11~20분)", -20, PENALTY, INDIVIDUAL, REGULAR_SESSION),
    SESSION_LATE_21_TO_30("정규 세션 지각 (21~30분)", -30, PENALTY, INDIVIDUAL, REGULAR_SESSION),

    SESSION_EARLY_LEAVE("정규 세션 조퇴", -30, PENALTY, INDIVIDUAL, REGULAR_SESSION),

    SESSION_ABSENCE("정규 세션 결석 (사전공유)", -50, PENALTY, INDIVIDUAL, REGULAR_SESSION),
    SESSION_TRUANCY("정규 세션 결석 (무단)", -100, PENALTY, INDIVIDUAL, REGULAR_SESSION),

    NO_VOTE("투표 미참여", -15, PENALTY, INDIVIDUAL, ACTIVITY),
    DELAY_DEPOSIT("입금 지연", -5, PENALTY, INDIVIDUAL, ACTIVITY),
    NO_SHOW_AFTER_PARTY("뒷풀이 신청 후 불참", -10, PENALTY, INDIVIDUAL, ACTIVITY),


    /** PENALTY: TEAM (팀 벌점) */
    STUDY_LATE_5_TO_9_ON_STUDY("스터디 지각 (5~9분)", -5, PENALTY, TEAM, STUDY_ON_TEAM),
    STUDY_LATE_10_TO_19_ON_STUDY("스터디 지각 (10~19분)", -10, PENALTY, TEAM, STUDY_ON_TEAM),
    STUDY_LATE_20_TO_29_ON_STUDY("스터디 지각 (20~29분)", -15, PENALTY, TEAM, STUDY_ON_TEAM),

    LATE_CLERK_UPLOAD_ON_STUDY("서기 업로드 지각 (스터디)", -10, PENALTY, TEAM, STUDY_ON_TEAM),
    DO_NOT_UPLOAD_CLERK_ON_STUDY("서기 미제출 (스터디)", -30, PENALTY, TEAM, STUDY_ON_TEAM),

    LATE_PROGRESS_TABLE_UPLOAD_ON_STUDY("진행표 업로드 지각 (스터디)", -10, PENALTY, TEAM, STUDY_ON_TEAM),
    DO_NOT_UPLOAD_PROGRESS_TABLE_ON_STUDY("진행표 미제출 (스터디)", -30, PENALTY, TEAM, STUDY_ON_TEAM),

    LATE_UPLOAD_CERTIFICATION_PHOTO_ON_STUDY("사진 업로드 지각 (스터디)", -5, PENALTY, TEAM, STUDY_ON_TEAM),
    LATE_SCHEDULE_ALERT_ON_STUDY("일정 공지 지각 (스터디)", -5, PENALTY, TEAM, STUDY_ON_TEAM),
    LATE_SUBMIT_FINAL_PRODUCT_ON_STUDY("결과물 제출 지각 (스터디)", -30, PENALTY, TEAM, STUDY_ON_TEAM),

    DO_NOT_ALERT_ABSENCE_OF_PERSONAL_REASON_ON_STUDY("개인 사유로 인한 결석 미공지 (스터디)", -10, PENALTY, TEAM, STUDY_ON_TEAM),
    DO_NOT_ALERT_TARDINESS_OF_PERSONAL_REASON_ON_STUDY("개인 사유로 인한 지각 미공지 (스터디)", -10, PENALTY, TEAM, STUDY_ON_TEAM),

    PROJECT_LATE_5_TO_9_ON_PROJECT("프로젝트 지각 (5~9분)", -5, PENALTY, TEAM, PROJECT_ON_TEAM),
    PROJECT_LATE_10_TO_19_ON_PROJECT("프로젝트 지각 (10~19분)", -10, PENALTY, TEAM, PROJECT_ON_TEAM),
    PROJECT_LATE_20_TO_29_ON_PROJECT("프로젝트 지각 (20~29분)", -15, PENALTY, TEAM, PROJECT_ON_TEAM),

    LATE_CLERK_UPLOAD_ON_PROJECT("서기 업로드 지각 (프로젝트)", -10, PENALTY, TEAM, PROJECT_ON_TEAM),
    DO_NOT_UPLOAD_CLERK_ON_PROJECT("서기 미제출 (프로젝트)", -30, PENALTY, TEAM, PROJECT_ON_TEAM),

    LATE_PROGRESS_TABLE_UPLOAD_ON_PROJECT("진행표 업로드 지각 (프로젝트)", -10, PENALTY, TEAM, PROJECT_ON_TEAM),
    DO_NOT_UPLOAD_PROGRESS_TABLE_ON_PROJECT("진행표 미제출 (프로젝트)", -30, PENALTY, TEAM, PROJECT_ON_TEAM),

    LATE_UPLOAD_CERTIFICATION_PHOTO_ON_PROJECT("사진 업로드 지각 (프로젝트)", -5, PENALTY, TEAM, PROJECT_ON_TEAM),
    LATE_SCHEDULE_ALERT_ON_PROJECT("일정 공지 지각 (프로젝트)", -5, PENALTY, TEAM, PROJECT_ON_TEAM),
    LATE_SUBMIT_FINAL_PRODUCT_ON_PROJECT("결과물 제출 지각 (프로젝트)", -30, PENALTY, TEAM, PROJECT_ON_TEAM),

    DO_NOT_ALERT_ABSENCE_OF_PERSONAL_REASON_ON_PROJECT("개인 사유로 인한 결석 미공지 (프로젝트)", -10, PENALTY, TEAM, PROJECT_ON_TEAM),
    DO_NOT_ALERT_TARDINESS_OF_PERSONAL_REASON_ON_PROJECT("개인 사유로 인한 지각 미공지 (프로젝트)", -10, PENALTY, TEAM, PROJECT_ON_TEAM),
    ;

    private String displayName;
    private Integer delta;
    private ScoreType scoreType;
    private AppliedTarget appliedTarget;
    private ActivityCategory category;

    public boolean isReward() {
        return scoreType.equals(REWARD);
    }

}
